# Generated by Django 3.2.7 on 2024-09-09 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0002_alter_vendas_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto_comprado', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 9, 9, 16, 15, 22, 87441))),
            ],
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 16, 15, 22, 87441)),
        ),
    ]
