# Generated by Django 3.2.7 on 2024-09-10 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0003_auto_20240909_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='total',
            new_name='valor_total',
        ),
        migrations.AlterField(
            model_name='compras',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 14, 37, 14, 595184)),
        ),
        migrations.AlterField(
            model_name='compras',
            name='nome_produto_comprado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='minha_dashboard.produto'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 14, 37, 14, 595184)),
        ),
    ]
