# Generated by Django 3.2.7 on 2024-09-11 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0004_auto_20240910_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.FloatField()),
                ('nome_despesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='minha_dashboard.produto')),
            ],
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 14, 31, 23, 248549)),
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
    ]
