# Generated by Django 3.2.7 on 2024-09-11 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0005_auto_20240911_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 15, 0, 28, 675580)),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 15, 0, 28, 673584)),
        ),
    ]
