# Generated by Django 3.2.7 on 2024-09-13 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0009_auto_20240912_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesas',
            old_name='valor_total',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 17, 6, 11, 634407)),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 17, 6, 11, 634407)),
        ),
    ]
