# Generated by Django 3.2.7 on 2024-09-16 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0020_auto_20240916_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 15, 49, 47, 550473)),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 15, 49, 47, 550473)),
        ),
    ]
