# Generated by Django 5.1.1 on 2024-10-04 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0021_auto_20240916_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 18, 3, 48, 587852)),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 18, 3, 48, 587852)),
        ),
    ]
